### ISSUE TITLE
Install fails on K8s < v1.19 clusters.

### ISSUE THREAD

**Issue by prasus** [traefik/mesh-helm-chart#8]
Greetings, I am in the middle of exploring service mesh offerings on our on-premise Kubernetes infrastructure running **Kubernetes v1.18.8** and would like to try-out traefik mesh as we are already using traefik for our ingress (it works great!) I have attempted deployment using the latest helm release (`traefik-mesh/traefik-mesh v1.4.0`) but the `helm install` leaves the controller pod in a `CrashLoop` state as seen below:

```
traefik-mesh-controller-6c688948bf-hggvm   0/1     Init:CrashLoopBackOff   4          113s  
```	

I see the following logs in the `traefik-mesh-prepare` init container:

```
kubectl -n traefik-mesh logs traefik-mesh-controller-5d888dcc67-5578q -c traefik-mesh-prepare
2020/10/06 03:34:04 command prepare error: unsupported SMI version: unable to find group "split.smi-spec.io" version "v1alpha3", got "v1alpha1"

```

`TraffikSplit` is served from v1alpha1 in k8s < v1.19, hence the init container fails with the error indicated above.
 
The helm deployment works fine if I attempt to deploy on a cluster running with k8s v1.19.

**k8s v1.18.8**
```
$ kubectl explain ts
KIND:     TrafficSplit
VERSION:  split.smi-spec.io/v1alpha1

DESCRIPTION:
     <empty>
```
**k8s v1.19.0**
```
kubectl explain ts
KIND:     TrafficSplit
VERSION:  split.smi-spec.io/v1alpha3

DESCRIPTION:
     <empty>
```
So the chart will only work on k8s v1.19 onwards and I believe we need to make changes [here](https://github.com/traefik/mesh/blob/93a3e67d429089d74be465fd179b73715de9d01c/pkg/k8s/smi.go) to make it compatible with k8s < v1.19. Thanks!

**Comment by prasus** [comment]
@ldez : I did a bit more investigation and this is not related to the helm chart, I have updated the description, appreciate if you could help to move this to the right queue. Thanks 🙂

**Comment by kevinpollet** [comment]
Hello @prasus,

Thanks for your interest in Traefik Mesh :)

The SMI CRDs are not shipped with k8s so it is the role of the mesh implementation to install them. The prepare command is failing because the version currently installed (by another mesh solution?) in your k8s cluster is not compatible. Traefik Mesh  is currently supporting the following version:

- Traffic Access [v1alpha2](https://github.com/servicemeshinterface/smi-spec/tree/master/apis/traffic-access/v1alpha2)
- Traffic Specs [v1alpha3](https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-specs/v1alpha3/traffic-specs.md)
- Traffic Split [v1alpha3](https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-split/v1alpha3/traffic-split.md) 

Can you try on a fresh installation of k8s 1.18?

**Comment by prasus** [comment]
@kevinpollet, you are right. I had tested `linkerd` before and it looks like the `linkerd uninstall` did not remove it completely, it works fine after removing all the linkerd components. thanks much for your help! 🙏

**Comment by kevinpollet** [comment]
You're welcome!
